### PR TITLE
(#116) Browser Back Button When Paging Through Results

### LINKED ISSUE #116: Browser Back Navigation Not Working When Paging Through Results
### Issue description
*Browser back navigation does not work when pager navigation is used to navigate through results*

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Visit https://www.cancer.gov/about-cancer/treatment/clinical-trials/adult-metastatic-brain-tumors/?pn=1
2. Using the pager navigation buttons, click on "Next"

### What's the expected result?
- Back browser button should be enabled, and should return user to page 1

### What's the actual result?
- Back browser button is disabled

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #116

* Added useEffect to set 'page' for 'pn' url parameter change when 'pn' doesn't match value in pager object

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH @mworrest @alinai 
Please can you review 
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-117?cfg=4
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-117/breast-cancer?cfg=0
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-117/trastuzumab?cfg=1

**Comment by VictoriaSunNIH** [comment]
I've tested this on edge, chrome and firefox and it works for me! @mworrest FYI - marking as passed UX

**Comment by mworrest** [comment]
Thanks, Victoria.

**Comment by alinai** [comment]
Looks good on Edge, Chrome, FF and IE. Thanks @seyilonge-nci.

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
