### PR TITLE
(#94) CIS Banner in IE

### LINKED ISSUE #94: IE is not displaying the No Trials banner properly for DTLP
### Issue description

IE is not displaying the No Trials banner properly for DTLP 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/develop/spiroplatin?cfg=1 on IE
2. The  No Trial banner is not displayed properly on IE
3. Go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/develop/c1234?cfg=0 on IE
4. The  No Trial banner is not displayed properly on IE

### What's the expected result?
- The No trials banner should display properly on IE 

### What's the actual result?
-The  No Trial banner is not displayed properly on IE (see the screen-shot)

### Additional details / screenshot
-
image

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by sarinapadilla**
Closes #94

* Update syntax for picture element in CISBanner - fixes browser issues

### CODE REVIEW

**Comment by sarinapadilla** [comment]
@VictoriaSunNIH @alinai @mworrest ready for testing: https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-115/chronic-fatigue-syndrome?cfg=0

**Comment by mworrest** [comment]
I don't have a pc :(

**Comment by VictoriaSunNIH** [comment]
@mworrest I'm on it and it shows up for me! Yay for easy testing!

**Comment by alinai** [comment]
Looks good on IE. Thanks @sarinapadilla!

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
