### PR TITLE
(#49) fixed the condition for intro text display

### LINKED ISSUE #49: When changing page on results, Intro text disappears
While looking at results, the intro text disappears while the fetch is happening and then reappears when results re-populate.  As a user, I would like the intro text to remain in place while paging through results.

> **ESTIMATE** 1

### Steps to reproduce the issue
Screen Shot 2021-04-05 at 10 54 00 AM

1.  Go to results
2.  Navigate to another page via pager
3.  See Intro text disappear and then re-appear once results come back

### What's the expected result?
- Once intro text is loaded, have it stay in place and prevent a major shift in position on the page

### PR DESCRIPTION
**Pull request by kate-mashkina**
- removed the condition of having query response
loading finished before displaying intro text

Close #49

### CODE REVIEW

**Comment by kate-mashkina** [comment]
@mworrest @alinai @VictoriaSunNIH url for review https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-53/breast-cancer?cfg=0

**Comment by mworrest** [comment]
I see the intro text is persistent while paging through results.

**Comment by VictoriaSunNIH** [comment]
Yep looks good to me too

**Comment by alinai** [comment]
Looks good to me on Chrome, FF, IE and Edge. Thanks @KateMashkinaNIH!

**Review by seyilonge-nci — APPROVED** [review]

**Review by sarinapadilla — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
