### PR TITLE
(#23) No Trials Found Page for Manual Listing Pages

### LINKED ISSUE #23: Story: No Trials Found Page for Manual Listing Pages
## As a user, I want to know what other options are available for me if there are no matching trials for a manual listing page, so that I can further engage with NCI.

> **ESTIMATE** 2 pts

### Acceptance Criteria

```gherkin
Scenario: No trials found for manual listing page
Given user navigates to “/”
When no trials are returned for the manual listing page
Then the system displays the H1
  Then the system displays the message: “There are currently no available trials.”
```
```gherkin
   Scenario: Page Load Analytics fires when a user views a manual listing page
    Given "trialListingPageType" is set to "Manual"
      And "pageTitle" is set to "Clinical Trials for Adult Metastatic Brain Tumors"
      And "analyticsPublishedDate" is set to "02/02/2011"
     When the user navigates to "/"
     Then the page title is "Clinical Trials for Adult Metastatic Brain Tumors"
      And browser waits
     Then there should be an analytics event with the following details
      | key                                         | value                                                                         | 
      | type                                        | PageLoad                                                                      | 
      | event                                       | TrialListingApp:Load:Results                                                  | 
      | page.name                                   | www.cancer.gov/                                                               | 
      | page.title                                  | Clinical Trials for Adult Metastatic Brain Tumors                             | 
      | page.metaTitle                              | Clinical Trials for Adult Metastatic Brain Tumors - National Cancer Institute | 
      | page.language                               | english                                                                       | 
      | page.type                                   | nciAppModulePage                                                              | 
      | page.channel                                | Clinical Trials                                                               | 
      | page.contentGroup                           | Clinical Trials: Custom                                                       | 
      | page.publishedDate                          | 02/02/2011                                                                    | 
      | page.additionalDetails.numberResults        | (int)0                                                                        | 
      | page.additionalDetails.trialListingPageType | manual parameters                                                             |
```
### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Tasks
- [x] Add route for Manual listing view
- [x] Wire-up fetching for api calls - @seyilonge-nci 
- [x] Add No Results component - @sarinapadilla 
- [x] Unit tests - @sarinapadilla @seyilonge-nci 
- [x] Have `NoResults` component displayed for no trials match - @sarinapadilla 
- [x] Integration tests - @kate-mashkina 
- [x] Analytics - @kate-mashkina 

### Technical Notes
- More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #23

* Added route for Manual listing
* Added HoC for computation and fetches before view display
* Added `NoListingType` as default placehoder
* Update config variables for Manual
* Add NoResults component
* Add unit test for NoResults component
* Added fetch for CTS api calls
* Fixed config assignments in index.html
* Added fetch for CTS api calls
* Added requestFilters for fetch call, updated and added unit tests
* Updated listings config values
* Updated test comment
* Updated api call to return no trials, updated conditional rendering for Manual component
* Updated Manual test
* Applied prettier formatting
* Added proxy
* Added mocks
* Added event tracking for manual page
* Added integration tests
* Updated unit test
* Moved NoResults to component dir, removed components not in use
* Added an extra step in integration test

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH 
Please can you review https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-25/transitional-cell-cancer-renal-pelvis-ureter?cfg=2

**Comment by VictoriaSunNIH** [comment]
Looks good to me! @mworrest for a quick look as needed!

**Comment by mworrest** [comment]
@seyilonge-nci  could you please bold the text "There are currently no available trials." so it matches the new style we set for CTS recently?

**Comment by seyilonge-nci** [comment]
> @seyilonge-nci could you please bold the text "There are currently no available trials." so it matches the new style we set for CTS recently?
> Example: https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?a=12&loc=1&rl=1&t=C8286&z=20874

@mworrest Updated with bold text.

**Comment by mworrest** [comment]
Thank you!

**Review by KateMashkinaNIH — APPROVED** [review]

**Pull request merged**
