### PR TITLE
(#71) Fix horizontal ruler

### LINKED ISSUE #71: At tablet and mobile breakpoint, double horizontal rule should not be displayed at the top when pager does not show up.
### Issue description
*Description of the issue*
At tablet and mobile breakpoint, when there is only one intervention,  we see two horizontal scroll bars without the pager in between (of course pager will not show as we have only one trial)
Compare : https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-70/bet-inhibitor-bms-986158?cfg=1&redirect=true  vs https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/bet-inhibitor-bms-986158?redirect=true

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-70/bet-inhibitor-bms-986158?cfg=1&redirect=true 
2. Switch to mobile breakpoint.
3. Two horizontal rule are displayed below the "Trials 1-1 of 1" 
4. Go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-70/bet-inhibitor-bms-986158?cfg=1&redirect=true 
5. Switch to tablet breakpoint.
6. Two horizontal rule are displayed below the "Trials 1-1 of 1" 

### What's the expected result?
- At tablet and mobile breakpoint, only one horizontal rule should be displayed below the "Trials 1-1 of 1" when pager is not displayed.

### What's the actual result?
- At mobile and tablet breakpoint, two horizontal rule are displayed below the "Trials 1-1 of 1" when pager is not displayed.

### Additional details / screenshot

image

image

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by KateMashkinaNIH**
- removed hr tags
- updated condition to display pager
- added disease and intervention scss
Closes #71

### CODE REVIEW

**Comment by KateMashkinaNIH** [comment]
@alinai @VictoriaSunNIH  @mworrest 

Here are the URLs to test :
1) Disease with pager : http://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-82/breast-cancer?cfg=0
2) Disease without pager : http://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-82/C9325?cfg=0
3) Intervention with pager - http://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-82/trastuzumab?cfg=1
4) Intervention without pager : http://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-82/C224?cfg=1

**Comment by bryanpizzillo** [comment]
@kate-mashkina I need to merge the fix to manual pages first, then you will need to rebase. If you added the same files, you will want to undo those before the rebase.

**Comment by alinai** [comment]
Looks good to me. Thanks @KateMashkinaNIH!

**Comment by mworrest** [comment]
Looks good to me as well.

**Pull request merged**
