### PR TITLE
(#17) Display Listing Results for Disease, Trial Type, Intervention

### LINKED ISSUE #17: Story: Display Listing Results for Disease, Trial Type & Intervention
## As a user, I would like to view the trial results for valid disease, trial type, and intervention code parameters on a dynamic trial listing page, along with links to the trial's description page, the brief summary of the trial, and the number of locations of the trial.

This should include:
- handling the routing for the disease dynamic URL
- fetching the ListingInformation for the given disease parameter
- fetching the results from the CTS API
- displaying the title, intro text, and listing results
- pager
- setting the metadata
- analytics
- page not found when the disease, trial type, or intervention doesn't exist
- No Trials Found redirect page
- Redirect ugly URLs to pretty URLs

The title and intro text for the disease, trial type, and intervention listing page is set according to given parameters.
H1: [Trial Type] Clinical Trials for [Disease Name] Using [Intervention Name]
Intro text:
```
<p>Clinical trials are research studies that involve people. The clinical trials on this list are for testing [trial type] methods for [disease name] that use [intervention name]. All trials on the list are NCI-supported clinical trials, which are sponsored or otherwise financially supported by NCI.</p><p>NCI’s <a href=\"/about-cancer/treatment/clinical-trials/what-are-trials\">basic information about clinical trials</a> explains the types and phases of trials and how they are carried out. Clinical trials look at new ways to prevent, detect, or treat disease. You may want to think about taking part in a clinical trial. Talk to your doctor for help in deciding if one is right for you.</p>
```

The metadata for the disease, trial type, and intervention listing pages is set according to the given parameters.
Title: [Trial Type] Clinical Trials for [Disease Name] Using [Intervention Name] - National Cancer Institute
Og title: [Trial Type] Clinical Trials for [Disease Name] Clinical Trials Using [Intervention Name]
Og url: [base host]/[disease-friendly-name-or-codes]/[trial-type]/[intervention-friendly-name-or-codes]
Description: "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find [trial type] clinical trials for [disease name] using [intervention name]."
Canonical URL: [canonical-host]/[disease-friendly-name-or-codes]/[trial type]/[intervention-friendly-name-or-codes]

Steal the locations code from the CTS App.

> **ESTIMATE** 5

#### General page
```gherkin
Scenario: View dynamic listing page results with disease, trial type, and intervention parameters
  Given the user navigates to "/C4872/treatment/C1647"
  And "trialListingPageType" is set to "Disease"
  Then the page displays the title 'Treatment Clinical Trials for Breast Cancer Using Trastuzumab'
    And the page displays the intro text under the title
    And  the page displays 'Trials 1-25 of 916' under the intro text
    And each result displays the trial object's brief_title as a link to the trial's description page
    And each result displays the trial object's brief_summary below the link for the trial
    And each result displays 'Locations: # locations' below the description
```

#### Title/Intro Text
```gherkin
Scenario: View dynamic listing page title and intro text with disease, trial type, and intervention parameters
Given the user navigates to "/C4872/treatment/C1647"
And "trialListingPageType" is set to "Disease"
  Then the system displays the page heading aka H1 as "Treatment Clinical Trials for Breast Cancer Using Trastuzumab"
  Then the system displays the following introductory text below the H1: "Clinical trials are research studies that involve people. The clinical trials on this list are testing treatment methods for breast cancer using Trastuzumab. All trials on the list are NCI-supported clinical trials, which are sponsored or otherwise financially supported by NCI."
  Then the system displays a paragraph break
  Then the system displays a second paragraph: "NCI’s basic information about clinical trials explains the types and phases of trials and how they are carried out. Clinical trials look at new ways to prevent, detect, or treat disease. You may want to think about taking part in a clinical trial. Talk to your doctor for help in deciding if one is right for you."
    And the text "basic information about clinical trials" links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/what-are-trials
  And the number of trials and pager displays below the intro text
  And the results appear below the number of trials and pager
```

#### Pager
``` gherkin
Scenario: Pager on dynamic listing page results with disease, trial type, and intervention parameters
  Given the user navigates to "/C4872/treatment/C1647"
  And "trialListingPageType" is set to "Disease"
    Then the page title is "Treatment Clinical Trials for Breast Cancer Using Trastuzumab"
   Then the system displays "Trials 1-25 of" "41"
    And the top pager is aligned to left on the same line as the number of trials on desktop and tablet
   And the bottom pager is aligned to left 
    And pager displays the following navigation options
      | pages  |
      | 1      |
      | 2      |
    And the page "1" is highlighted
```
```gherkin
Scenario: Mobile Pager Display
  Given user navigates to a listing page results URL
  Then the system returns the results page for cancer
    Then a horizontal rule is displayed below the "Trials 1-25 of XXX" 
    Then a top pager is displayed aligned to the right
    Then a horizontal rule is displayed below the pager
    Then the result items are displayed 
    Then a horizontal rule is displayed 
    Then the bottom pager is displayed aligned to the right
```

#### Metadata
```gherkin
Scenario: View dynamic listing page metadata with disease, trial type, and intervention parameters
  Given the site name is "National Cancer Institute"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And "trialListingPageType" is set to "Disease"
When user navigates to "/C4872/treatment/C1647"
  Then the title tag should be "Treatment Clinical Trials for Breast Cancer Using Trastuzumab - National Cancer Institute 
    And there is a meta tag with a property "og:title" and content "Treatment Clinical Trials for Breast Cancer Using Trastuzumab"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/breast-cancer/treatment/trastuzumab"
    And there is a meta tag with a property "description" and content "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find clinical trials testing trastuzumab in the treatment of breast cancer."
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/breast-cancer/treatment/trastuzumab"
```

#### Analytics
```gherkin
  Scenario: Page Load Analytics fires when a user views a dynamic listing page with disease, trial type, and intervention parameters
    Given "baseHost" is set to "http://localhost:3000"
       And "canonicalHost" is set to "https://www.cancer.gov"
       And "siteName" is set to "National Cancer Institute"
       And "channel" is set to "Clinical Trials"
       And "trialListingPageType" is set to "Disease"
    When the user navigates to "/C4872/treatment/C1647"
    Then there should be an analytics event with the following details
      | key                                          | value                                                                                      |
      | type                                         | PageLoad                                                                                   |
      | event                                        | TrialListingApp:Load:Results                                                               |
      | page.name                                    | www.cancer.gov/breast-cancer/treatment/trastuzumab                                         |
      | page.title                                   | Treatment Clinical Trials for Breast Cancer Using Trastuzumab                              |
      | page.metaTitle                               | Treatment Clinical Trials for Breast Cancer Using Trastuzumab - National Cancer Institute  |
      | page.language                                | english                                                                                    |
      | page.type                                    | nciAppModulePage                                                                           |
      | page.channel                                 | Clinical Trials                                                                            |
      | page.contentGroup                            | Clinical Trials: Custom                                                                    |
      | page.publishedDate                           | 02/02/2011                                                                                 |
      | page.additionalDetails.numberResults         | [(int) results total]                                                                      |
      | page.additionalDetails.trialListingPageType  | disease                                                                                    |
      | page.additionalDetails.diseaseName           | breast cancer                                                                              |
      | page.additionalDetails.trialType             | treatment                                                                                  |
      | page.additionalDetails.interventionName      | trastuzumab                                                                                |
```

#### Page Not Found for invalid Disease, Trial Type, or Intervention
```gherkin
Scenario: Page Not Found displays when a user views a dynamic listing page with invalid disease, trial type, or intervention parameters
Given user navigates to “/C123456/chicken/C56789”
And "trialListingPageType" is set to "Disease"
When the user has entered an incorrect disease, trial type, or intervention
Then the system redirects users to a 404 page 
     Then page title on error page is "Page Not Found"
     And the search bar appears below the text
     And the following links and texts exist on the page: "We can't find the page you're looking for." Visit the homepage, browse by cancer type, or use the search below." "Have a question? Get in touch."
  
      | https://www.cancer.gov          | homepage      | 
      | https://www.cancer.gov/types    | cancer type   | 
      | https://www.cancer.gov/contact  | Get in touch  |

     And the system returns a 404 status code
```
```gherkin
Given the application returns a "Page not found" message
  Then the page should contain the markup <meta name="prerender-status-code" content="404">
```

```gherkin
Scenario: Page Load Analytics fires for a 404 with invalid disease, trial type, or intervention
 Given "trialListingPageType" is set to "Disease"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "analyticsPublishedDate" is set to "02/02/2011"
    And "siteName" is set to "National Cancer Institute"
 When the user navigates to "/C123456/chicken/C56789"
   Then page title on error page is "Page Not Found"
    And browser waits
   Then there should be an analytics event with the following details

| key                                          | value                                            |
| type                                         | PageLoad                                         |
| event                                        | TrialListingPageApp:Load:PageNotFound            |
| page.name                                    | www.cancer.gov/C123456/chicken/C56789            |
| page.title                                   | Page Not Found                                   |
| page.metaTitle                               | Page Not Found                                   |
| page.language                                | english                                          |
| page.type                                    | nciAppModulePage                                 |
| page.channel                                 | Clinical Trials                                  |
| page.contentGroup                            | Clinical Trials: Custom                          |
| page.additionalDetails.trialListingPageType  | disease                                          |
```

#### No Trials Found page
```gherkin
Scenario: Page redirects and displays No Trials Found Page for Disease, Trial Type, and Intervention
Given user navigates to “/C1234/treatment/C90960”
And "trialListingPageType" is set to "Disease"
  When no trials are returned for the disease and trial type and intervention
  Then the system redirects users to /notrials?p1=spiroplatin&p2=treatment&p3=insulin-beef
  Then the system displays the H1
  Then the system displays the message: "There are no NCI-supported clinical trials for spiroplatin treatment using insulin beef at this time. You can try a new search or contact our Cancer Information Service to talk about options for clinical trials.”
Then the system displays the banner for “Questions about Clinical Trials?” 
```
```gherkin
Scenario: Status Code Returned for no trials found For Disease, Trial Type, and Intervention
Given user navigates to “/C1234/treatment/C90960”
And "trialListingPageType" is set to "Disease"
  When no trials are returned for the disease and trial type and intervention
  Then the system redirects users to /notrials?p1=spiroplatin&p2=treatment&p3=insulin-beef
Then the page should return a 404 status code.
```

#### Redirect ugly URL to pretty URL
```gherkin
Scenario: Page redirects to pretty URL if codes are given for Disease, Trial Type, and Intervention
Given user navigates to “/C4872/treatment/C1647”
And "trialListingPageType" is set to "Disease"
  When a mapping exists for C4872
  And a mapping exists for C1647
  Then the system should redirect the URL to “/breast-cancer/treatment/trastuzumab”
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [x] Add GetTrialType action
- [x] Add /:codeOrPurl/:type/:interCodeOrPurl route
- [x] Update config variables for browserTitle, introText, metaDescription, noTrialsHtml, pageTitle
    a. They need to be set based on Disease Page Type: DiseaseOnly, DiseaseTrialType, DiseaseTrialTypeIntervention
- [x] Update App.js with routeParamMap for Disease/Type/Intervention
- [x] Update useListingSupport for type 'type'
- [x] Update CTLViewsHoC with 'trial-type' action
- [x] Update ugly -> pretty URL name redirect in HoC
- [x] Update Disease component for updated config object destructuring
- [ ] Create Disease/Type/Intervention component
    a. Set up request filters for CTS API call
    b. Set up No Trials redirect
    c. Update analytics event
    d. Update NoTrialsFound component for extra parameters (need to know how to set up context for text replacement based on requested page params)

### Technical Notes
- More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #17

* Added route for disease/type/intervention
* Updated config structure for dynamic listing

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH @mworrest Please can you review

No Trials Found
-----------------
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-84/C4872/treatment/C1647?cfg=0

Page Not Found
-----------------
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-84/C123456/chicken/C56789?cfg=0

Disease/Trial Type/Intervention Results Display
-----------------------------------------------
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-84/C1234/treatment/C90960?cfg=0

**Comment by VictoriaSunNIH** [comment]
@mworrest - this all looked good to me.  Please validate and flip the label if things look good from the UX side. Thanks!

**Comment by mworrest** [comment]
Looks good to me as well.

**Comment by kate-mashkina** [comment]
it should not render prerender-status-code meta tag if no redirect happened

Screen Shot 2021-05-13 at 9 20 13 AM

**Pull request merged**
