### PR TITLE
(#15) Page Not Found for routes missing params

### LINKED ISSUE #15: Story: Create 404 for /disease or /intervention without additional parameters
## As a [role], I want [feature], so that [benefit]

If a user attempts to access /about-cancer/treatment/clinical-trials/disease or /about-cancer/treatment/clinical-trials/intervention , the system shall return a 404 status code and display the cancer.gov 404 page.

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: Page not found should be displayed when a user visits the disease or intervention page without any additional parameters
    Given the user is viewing the dynamic listing page for disease without any parameters
     Then page title on error page is "Page Not Found"
     And the search bar appears below the text
     And the following links and texts exist on the page: "We can't find the page you're looking for." Visit the homepage, browse by cancer type, or use the search below." "Have a question? Get in touch."
  
      | https://www.cancer.gov          | homepage      | 
      | https://www.cancer.gov/types    | cancer type   | 
      | https://www.cancer.gov/contact  | Get in touch  |
```

#### Analytics
```gherkin
Scenario: Page Load Analytics fires for a 404 on disease or intervention page without any additional parameters
  Given "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "siteName" is set to "National Cancer Institute"
    And "channel" is set to "Publications"
    And "analyticsPublishedDate" is set to "02/02/2011"
    And "analyticsName" is set to "???"
   When the user is viewing the dynamic listing page for disease without any parameters
   Then page title on error page is "Page Not Found"
    And browser waits
   Then there should be an analytics event with the following details

| key                                          | value                                            |
| type                                         | PageLoad                                         |
| event                                        | TrialListingPageApp:Load:PageNotFound            |
| page.name                                    | www.cancer.gov/disease                           |
| page.title                                   | Page Not Found                                   |
| page.metaTitle                               | Page Not Found                                   |
| page.language                                | english                                          |
| page.type                                    | nciAppModulePage                                 |
| page.channel                                 | Clinical Trials                                  |
| page.contentGroup                            | ???                                              |
| page.additionalDetails.trialListingPageType  | [disease | intervention]                         |

```

### Resources:
* Web Page:
    * https://www.cancer.gov/foo (to see the error page)

### Notes
Anything outside of the app routes should be handled by Drupal for an actual 404. A "404" in the app should only happen for:
* On the real web site, no parameters are given after /disease/ or /intervention
* On react app dev, someone asks for a route not within the app

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by sarinapadilla**
* Closes #15

* Update index.html with updated config variables
* Add parameter-less routes leading to PageNotFound component
* Update PageNotFound component unit tests
* Add parameter-less PageNotFound integration tests
* Add integration test cypress JS
* Remove sample integration test

### CODE REVIEW

**Comment by sarinapadilla** [comment]
@VictoriaSunNIH @arcepaul ready for review!
Here's the two links you'll be checking for Page Not Found:
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-26/?cfg=0 (Disease)
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-26/?cfg=1 (Intervention)

(Technically it will work for any route with ?cfg=0 or ?cfg=1...but that's because we haven't set up the other routes yet)

**Review by arcepaul — APPROVED** [review]

**Comment by VictoriaSunNIH** [comment]
Looks good to me - @mworrest can you take a quick look and make sure it looks right to you too? :)  Thanks!

**Comment by sarinapadilla** [comment]
@kate-mashkina please take a look at this as well for QA review!

**Comment by alinai** [comment]
Everything is looking good other than the Search.

**Comment by arcepaul** [comment]
Looking at the search component of the No Page found, can we make it a form for semantics and functionality?

**Review by arcepaul — CHANGES_REQUESTED** [review]
Please address the form elements on Page Not Found

**Comment by sarinapadilla** [comment]
@arcepaul updated with a form so both search button click and pressing enter perform a search.
@VictoriaSunNIH @mworrest @kate-mashkina please confirm everything is looking/working right!

**Comment by VictoriaSunNIH** [comment]
Search works and looks good to me now! Thanks @sarinapadilla ! Waiting on Michelle before i "flip the label" :)

**Comment by mworrest** [comment]
Please increase bottom margin on H1 so that it matches that of drug dictionary and other pages of the site. 
Drug dictionary page not found:
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/cyclosfdasgerine

**Comment by sarinapadilla** [comment]
@mworrest H1 bottom margin fixed!

**Comment by mworrest** [comment]
Thank you @sarinapadilla and thank you @alinai for noticing!

**Review by arcepaul — APPROVED** [review]

**Comment by alinai** [comment]
Search looks good on both pages.

**Pull request merged**
