### PR TITLE
(#62) Remove dictionary popup from Intro Text

### LINKED ISSUE #62: Remove dictionary popup from default content
### Issue description

Placeholder - needs stakeholder approval to remove dictionary popup from default content

> **ESTIMATE** 1

### What's the expected change?
- Updates to the text to remove the link to NCI Support Trials, as well as the context around that link.

### What's the current functionality?
- The current popup link is broken on prod and should be removed

### What's the updated acceptance criteria?
```gherkin
Given the user navigates to "/C4872"
And "trialListingPageType" is set to "Disease"
  Then the system displays the page heading aka H1 as "Breast Cancer Clinical Trials"
  Then the system displays the following introductory text below the H1: "Clinical trials are research studies that involve people. The clinical trials on this list are for breast cancer. All trials on the list are NCI-supported clinical trials, which are sponsored or otherwise financially supported by NCI."
  Then the system displays a paragraph break
  Then the system displays a second paragraph: "NCI’s basic information about clinical trials explains the types and phases of trials and how they are carried out. Clinical trials look at new ways to prevent, detect, or treat disease. You may want to think about taking part in a clinical trial. Talk to your doctor for help in deciding if one is right for you."
    And the text "basic information about clinical trials" links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/what-are-trials
  And the number of trials and pager displays below the intro text
  And the results appear below the number of trials and pager
```
```gherkin
Given the user navigates to "/C1647"
And "trialListingPageType" is set to "Intervention"
  Then the system displays the page heading aka H1 as "Clinical Trials Using Trastuzumab"
  Then the system displays the following introductory text below the H1: "Clinical trials are research studies that involve people. The clinical trials on this list are studying Trastuzumab. All trials on the list are NCI-supported clinical trials, which are sponsored or otherwise financially supported by NCI."
  Then the system displays a paragraph break
  Then the system displays a second paragraph: "NCI’s basic information about clinical trials explains the types and phases of trials and how they are carried out. Clinical trials look at new ways to prevent, detect, or treat disease. You may want to think about taking part in a clinical trial. Talk to your doctor for help in deciding if one is right for you."
    And the text "basic information about clinical trials" links to https://www.cancer.gov/about-cancer/treatment/clinical-trials/what-are-trials
  And the number of trials and pager displays below the intro text
  And the results appear below the number of trials and pager
```

### Additional details / screenshot
- Screenshot

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

### PR DESCRIPTION
**Pull request by sarinapadilla**
Closes #62

* Update introText in index.html
* Update introText in beforeEach.js
* Update integration tests

### CODE REVIEW

**Comment by sarinapadilla** [comment]
@VictoriaSunNIH @mworrest @alinai ready for testing!
Disease: https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-77/breast-cancer?cfg=0
Intervention: https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-77/bevacizumab?cfg=1

**Comment by mworrest** [comment]
Is "breast cancer" supposed to be capitalized like in the AC? I think the answer is no. https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-77/breast-cancer?cfg=0

**Comment by VictoriaSunNIH** [comment]
> Is "breast cancer" supposed to be capitalized like in the AC? I think the answer is no. https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-77/breast-cancer?cfg=0

You are correct in that it should not be capitalized and I will adjust the AC :)

**Comment by alinai** [comment]
I have same question as @mworrest. Also, which H1 text is correct the one on AC or on  https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-77/breast-cancer?cfg=0?

**Comment by VictoriaSunNIH** [comment]
> I have same question as @VictoriaSunNIH . Also, which H1 text is correct the one on AC or on https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-77/breast-cancer?cfg=0?

Copy and paste error - it should be "Breast Cancer Clinical Trials". I've updated the AC

**Comment by mworrest** [comment]
With those questions answered, I think it passes UX review.

**Comment by alinai** [comment]
Looks good to me too! Thanks @sarinapadilla!

**Review by KateMashkinaNIH — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
