### PR TITLE
(#95) Added empty page options container

### LINKED ISSUE #95: Listing apps should accommodate for delighter
### Issue description
*Description of the issue*
Currently both manual and dynamic pages do not have page options as it was removed intentionally - which caused drupal not render delighter.

The solution is to add an empty page options block to both apps

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by kate-mashkina**
Closes #95

### CODE REVIEW

**Comment by kate-mashkina** [comment]
https://ncigovcdode417.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/childhood-embryonal-tumors - Page that is pointed to the bug fix branch

**Comment by kate-mashkina** [comment]
@VictoriaSunNIH could you do the honors of flipping the UX label?

**Comment by VictoriaSunNIH** [comment]
I see it working! Thanks!

**Comment by arcepaul** [comment]
@kate-mashkina why not add it to App.js so that it is there for all views.?  In this case, the div would have to be added to every view individually.

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
