### PR TITLE
(#86) Maintain Scroll Position For Back Navigation

### PR DESCRIPTION
**Pull request by seyilonge-nci**
* Added initial commit
* Added `useScrollRestoration` hook to handle custom scrolling
* Updated Disease and Manual components
* Conditional rendering for hook with component, removed scroll test on Manual
* Swapped window.sessionStorage for scroll state with window.history

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH, @mworrest, @alinai 
Please can you review 
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-113/?cfg=4
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-113/trastuzumab?cfg=1

| Test Scenario  | Expected Scroll Position  |
|---|---|
| Initial page load | Top of page |
| Scroll to somewhere in the middle of the page, click on link, and use browser back button  | Previous position in the middle of the page|
| Scroll to bottom of page, click on title link, and use browser back button | Previous position at the bottom of the page |
| Scroll to bottom of page, click on page 2 using the pager, use browser back button | Top of page |
| Scroll to bottom of page, click on page 2 using the pager, use the pager previous link | Top of page |

Note: A page refresh at any point will not have the scroll position at the top of the page, but at the same scroll position.

**Comment by VictoriaSunNIH** [comment]
@seyilonge-nci, @alinai 

2 issues we found:

1. IE is not remembering the position when we hit the back button, but is instead taking us to the manual listing page (URL without parameters)
2. Go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-113/?cfg=4&hideJumpMenu=true&pn=5
    Scroll all the way down
    Click pn=7 from the bottom pager
    Now you are at the top of the page (which is correct)
    scroll down again and click the title link at the bottom
    Use the browser back option
    You reach the top of the page but should be taken to where the title was

cc: @santwuma

**Comment by seyilonge-nci** [comment]
> @seyilonge-nci, @alinai
> 
> 2 issues we found:
> 
> 1. IE is not remembering the position when we hit the back button, but is instead taking us to the manual listing page (URL without parameters)
> 2. Go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-113/?cfg=4&hideJumpMenu=true&pn=5
>    Scroll all the way down
>    Click pn=7 from the bottom pager
>    Now you are at the top of the page (which is correct)
>    scroll down again and click the title link at the bottom
>    Use the browser back option
>    You reach the top of the page but should be taken to where the title was
> 
> cc: @santwuma

@VictoriaSunNIH listed issues fixed, please confirm.

**Comment by alinai** [comment]
We noticed that when we copy and paste https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-113/trastuzumab?cfg=1&hideJumpMenu=true on a tab in Chrome and then copy and paste https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-113/?cfg=4&hideJumpMenu=true in the same tab and then use click the browser back option, we come to the 
Trastuzumab DTLP page. But if we do the same on IE, we get Page Not Found on clicking the browser back option. Per @seyilonge-nci , this is a known IE issue in the way it handles back and forward caching.

**Pull request merged**
