### PR TITLE
(#14) Redirect Ugly Urls to Pretty Urls for Disease

### LINKED ISSUE #14: Story: Redirect Ugly Urls to Pretty Urls for disease
## As the system, I want to be able to redirect users to pretty URLs for the dynamic listing pages, so that the pages are more user and SEO friendly.

While the below ACs reference the pretty URL, we need to make sure this also works for situations where a redirect doesn't exist for a C-code so that if the user inputs a Disease C-Code or an Intervention C-Code in the URL, they can still visit a page but it just doesn't have a pretty URL.

> **ESTIMATE** 2 / 5 

### Acceptance Criteria

```gherkin
  Scenario: Page redirects to pretty URL if codes are given for Disease
    Given "trialListingPageType" is set to "Disease"
      And "pageTitle" is set to "{{disease_label}} Clinical Trials"
    Given the user navigates to "/C4872?cfg=0"
     Then the user is redirected to "/breast-cancer?redirect=true"
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

* Check for the use case where there is no pretty-url set for a concept ID, as this will not redirect
* Find a c-code that fits this test case

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [x] Add logic for redirect to `CTLViewsHoC`
- [x] Add unit test for redirect
- [x] Add integration test

### Technical Notes
- More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #14

* Added feature file for integration test

### CODE REVIEW

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH @mworrest @blilianyu 
Please review https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-39/C4872?cfg=0

**Comment by VictoriaSunNIH** [comment]
tested a few single codes, as well as multiple codes. looks good

**Comment by kate-mashkina** [comment]
@alinai could you take a look at the PR? https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-39/C4872?cfg=0

**Comment by alinai** [comment]
> @alinai could you take a look at the PR? https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-39/C4872?cfg=0

Sure

**Review by kate-mashkina — APPROVED** [review]

**Review by sarinapadilla — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
