### PR TITLE
(#129) NPM Audit Fix

### LINKED ISSUE #129: Fix npm audit issues
There are a number of modules that need updating to resolve security items in back-end tooling.

### PR DESCRIPTION
**Pull request by alerosad**
Closes #129

https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-142/breast-cancer?cfg=0

### CODE REVIEW

**Comment by alerosad** [comment]
the other packages when updated cause breaking changes, these include:
npm install --save-dev webpack-dev-server@4.6.0
npm install --save-dev node-sass@7.0.0

**Comment by alerosad** [comment]
Let me know about the remaining packages, if any of them need to be updated. If so, I'll go ahead and continue trying to get them to work

**Comment by alerosad** [comment]
I tried updating react-dev-utils to 9.0.0 and to 12.0.0, however, both versions break the code. It States: `Error: Cannot find module 'react-dev-utils/WatchMissingNodeModulesPlugin'`
I think in one of the updated versions they may have removed this part of the package

**Comment by alerosad** [comment]
https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-142
https://www.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer/


@kate-mashkina @alinai

**Review by kate-mashkina — APPROVED** [review]

**Comment by kate-mashkina** [comment]
This has passed QA review 
Noting here for documentation purposes that IE is not displaying delighter, but so is develop branch - this should be reassessed on a diff env (ODE)

**Comment by bryanpizzillo** [comment]
@alerosad can you please note on this ticket why there are so many line ending changes? I.E. what package update changed the linter requirements?

Normally my expectation when there is an `npm audit --fix` is that only the package.json would be updated.

**Comment by alerosad** [comment]
fixed linting issue

**Review by arcepaul — APPROVED** [review]

**Pull request merged**
